### ISSUE TITLE
bug: config.yaml里面存在多条metrics时, 偶尔会出现query 解析错误导致查询失败

### ISSUE THREAD

**Issue by linlanniao** [fengxsong/queryexporter#1]
**example:**

config.yaml
```yaml
enableProfile: false
enableGoCollect: false
logFormat: json
logLevel: debug
servers:
  - name: doris
    uri: ***
metrics:
  mysql:
  - name: errors_total_1m
      query: |
        SELECT  site, count(*) As error_count FROM  tableAAA  GROUP BY site;
      variableValue: "error_count"
      variableLabels:
        - site
      type: gauge
      datasources:
        - name: doris
          database: doris
          table: tableAAA
  - name: errors_total_1m
      query: |
        SELECT  site, count(*) As error_count FROM  tableBBB  GROUP BY site;
      variableValue: "error_count"
      variableLabels:
        - site
      type: gauge
      datasources:
        - name: doris
          database: doris
          table: tableBBB
```

**Want:**
```SQL
-- query to tableAAA
SELECT  site, count(*) As error_count FROM  tableAAA  GROUP BY site;

-- query to tableBBB
SELECT  site, count(*) As error_count FROM  tableBBB  GROUP BY site;

```

**Actual:**
```SQL
-- query to tableAAA
SELECT  site, count(*) As error_count FROM  tableAAA  GROUP BY site;

-- query to tableBBB, <- Wrong sql
SELECT  site, count(*) As error_count FROM  tableAAA  GROUP BY site;
```

**errors**
```bash
  curl localhost:9696/metrics
```

```html
An error has occurred while serving metrics:

5 error(s) occurred:
* collected metric "queryexporter_mysql_errors_total_1m" { label:{name:"database" value:"doris"} label:{name:"name" value:"doris1"} label:{name:"site" value:""} label:{name:"table" value:"error_logs"} gauge:{value:0}} was collected before with the same name and label values
* collected metric "queryexporter_mysql_errors_total_1m" { label:{name:"database" value:"doris"} label:{name:"name" value:"doris1"} label:{name:"site" value:""} label:{name:"table" value:"error_logs"} gauge:{value:0}} was collected before with the same name and label values
* collected metric "queryexporter_mysql_errors_total_1m" { label:{name:"database" value:"doris"} label:{name:"name" value:"doris1"} label:{name:"site" value:""} label:{name:"table" value:"error_logs"} gauge:{value:0}} was collected before with the same name and label values
* collected metric "queryexporter_mysql_errors_total_1m" { label:{name:"database" value:"doris"} label:{name:"name" value:"doris1"} label:{name:"site" value:""} label:{name:"table" value:"error_logs"} gauge:{value:0}} was collected before with the same name and label values
* collected metric "queryexporter_mysql_errors_total_1m" { label:{name:"database" value:"doris"} label:{name:"name" value:"doris1"} label:{name:"site" value:""} label:{name:"table" value:"error_logs"} gauge:{value:0}} was collected before with the same name and label values
```
